apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: codex
  namespace: default
spec:
  type: secretstores.local.file
  metadata:
  - name: secretsFile
    value: "/secrets/dapr_secret.json"